DocumentParse:
  vllm: False   # 默认不开启vllm推理加速
  input_path: "data/raw"
  output_path: "data/process"
  auto_clean: "False"

Chunk:
  overlap: 150
  max_length: 600      # 对应 20% 的余地 (500 * 1.2)
  chunk_size: 500
  input_path: "data/process"
  output_path: "data/chunk"
  threshold: 0.2       # 切片上下文弹性比例
  top_k: 3      # 关键字个数

LanceDB:
  input_path: "data/chunk"
  output_path: "data/vector_database"
  table_name: "chunks"
  top_k: 5
  vector_dim: 768      # 新增：向量维度

LLM:
  temperature: 0.8
  think: true

Embedding:
  input_path: "data/chunk"
  dim: 768